version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    environment:
      HOST_DB_TAG: 'mysql'
      USER_DB_TAG: 'root'
      PWD_DB_TAG: 'root'
      DB_TAG: 'demo.tag.ong.br'
      YII_DEBUG: 'true'
    networks:
      - tag-v3-network
  
  mysql:
    image: mysql:5.7
    container_name: mysql-api
    restart: always
    command: mysqld --sql_mode=""
    ports:
      - 3306:3306
    expose:
      - 3306
    deploy:
        resources:
            limits:
              cpus: '2'
              memory: 1024M
            reservations:
              cpus: '1'
              memory: 1GB
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: tag
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./db:/var/lib/mysql
      # - .\dump.sql:/docker-entrypoint-initdb.d/dump.sql
      # - ./dump-data.sql:/docker-entrypoint-initdb.d/dump-data.sql
    networks:
      - tag-v3-network
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
    networks:
      - tag-v3-network

networks:
  tag-v3-network:

volumes:
  db-volume:
